# Generated by Django 4.1.1 on 2022-11-27 02:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('mnemonic', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_description', models.CharField(max_length=250)),
                ('course_number', models.CharField(max_length=100)),
                ('course_mnemonic', models.CharField(max_length=100)),
                ('course_alias', models.CharField(max_length=200, null=True)),
                ('course_description_compressed', models.CharField(max_length=250, null=True)),
                ('section_instructor', models.CharField(max_length=100)),
                ('section_instructor_compressed', models.CharField(max_length=100, null=True)),
                ('section_meetings', models.CharField(max_length=1000)),
                ('section_meetings_compressed', models.CharField(max_length=1000, null=True)),
                ('section_code', models.IntegerField()),
                ('section_number', models.CharField(max_length=10)),
                ('section_component', models.CharField(max_length=10)),
                ('section_credits', models.CharField(max_length=100)),
                ('section_topic', models.CharField(max_length=250)),
                ('section_topic_compressed', models.CharField(max_length=250, null=True)),
                ('section_waitlist', models.IntegerField()),
                ('section_waitlist_cap', models.IntegerField()),
                ('section_enrollment_free', models.IntegerField()),
                ('section_enrollment_total', models.IntegerField()),
                ('section_enrollment_capacity', models.IntegerField()),
                ('update_status', models.BooleanField(default=True)),
                ('course_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lousprime.department')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=50)),
                ('credits', models.IntegerField(null=True)),
                ('sections', models.ManyToManyField(to='lousprime.section')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='socialaccount.socialaccount')),
                ('user_friends', models.ManyToManyField(blank=True, related_name='user_friends', to='socialaccount.socialaccount')),
                ('user_schedule', models.ManyToManyField(blank=True, to='lousprime.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='socialaccount.socialaccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('comment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lousprime.schedule')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
    ]
